server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url:               jdbc:postgresql://localhost:5432/test
    username:          postgres
    password:          postgres

logging:
  config: classpath:./log4j2.xml